- Resources/Prototypes/Loadouts/loadout_groups.yml
Added the server pins to the loadout section. 
**Changelog**
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Added server pins to the trinket section in character loadouts.
> pins loadout

- .github/workflows/publish.yml
- Tools/gen_build_info.py
> Attempting some proper workflow for CDN and Manifest update stuff.

- Resources/Prototypes/lobbyscreens.yml
- Resources/Prototypes/secret_weights.yml
- Resources/Textures/LobbyScreens/attributions.yml
- Resources/Textures/LobbyScreens/stationcafe.png.yml
Adding the lobby art made by Amatiramasu
- Added as a PNG because the size wasn't playing nice with webp. 
- Should ask them to modify it to be the correct ratio at some point. 
Removing Revolutionaries from secret rotation
- commented out Revolutionaries
- Moved the weight for that preset to survival
> Added new lobby art and took revs out of rotation.

- Resources/Prototypes/GameRules/unknown_shuttles.yml
- Resources/Prototypes/Loadouts/Jobs/Cargo/quartermaster.yml
- Resources/Prototypes/Loadouts/Jobs/Civilian/janitor.yml
- Resources/Prototypes/Loadouts/Jobs/Civilian/passenger.yml
- Resources/Prototypes/Loadouts/Jobs/Command/captain.yml
- Resources/Prototypes/Loadouts/Jobs/Command/head_of_personnel.yml
- Resources/Prototypes/Loadouts/Jobs/Engineering/chief_engineer.yml
- Resources/Prototypes/Loadouts/Jobs/Engineering/station_engineer.yml
- Resources/Prototypes/Loadouts/Jobs/Medical/chief_medical_officer.yml
- Resources/Prototypes/Loadouts/Jobs/Medical/medical_doctor.yml
- Resources/Prototypes/Loadouts/Jobs/Science/research_director.yml
- Resources/Prototypes/Loadouts/Jobs/Science/scientist.yml
- Resources/Prototypes/Loadouts/Jobs/Security/head_of_security.yml
- Resources/Prototypes/Loadouts/Jobs/Security/security_officer.yml
Reduce clothing timers and bring honk and syndi evac shuttles back into rotation
Most folks on Harmony are experienced players and would like their clothing swag. Making it an hour or three to get it means they have to have at least done a shift or two for them. 
Re-introducing shuttles since honk shuttle is less spidery. I also want to see if the syndi evac shuttle is going to cause as many issues as we worried.
Just changed some minor config settings.
> Keld reducetimers

- Resources/Prototypes/GameRules/events.yml
The only file changed is the events.yml under Resources/Prototypes/GameRules/events.yml
This is for a few reasons. I also feel there has been an extreme overabundance of round ending mdiround antagonists and that this is extremely disruptive and repetitive. Ninjas, Dragons, and Lone Ops happen too often. This problem is more noticeable at lower populations were a single space dragon can effortlessly kill everybody on the station. Harmony Round 297 had 22 players online, and with how often these antagonists roll we got both a Space Dragon AND Lone Op with only half of those players actually being a character instead of a ghost. This makes for extreme steamrolling on lower population that very likely won't be enjoyed by the players being steamrolled. SpiderSpawn as one example have a weight …
> Midround antag weights

- Resources/Maps/Harmony/Shuttles/WizDen-ERT-Shuttles/ERT-Large-Base.yml
- Resources/Maps/Harmony/Shuttles/WizDen-ERT-Shuttles/ERT-Large-Med-Sec.yml
- Resources/Maps/Harmony/Shuttles/WizDen-ERT-Shuttles/ERT-Medium-Base.yml
- Resources/Maps/Harmony/Shuttles/WizDen-ERT-Shuttles/ERT-Medium-BasePlus.yml
- Resources/Maps/Harmony/Shuttles/WizDen-ERT-Shuttles/ERT-Medium-Eng-Jani.yml
- Resources/Maps/Harmony/Shuttles/WizDen-ERT-Shuttles/ERT-Medium-Med.yml
- Resources/Maps/Harmony/Shuttles/WizDen-ERT-Shuttles/ERT-Medium-Sec.yml
- Resources/Maps/Harmony/Shuttles/WizDen-ERT-Shuttles/ERT-Small-Base.yml
- Resources/Maps/Harmony/Shuttles/WizDen-ERT-Shuttles/ERT-Small-CBURN.yml
- Resources/Maps/Harmony/Shuttles/WizDen-ERT-Shuttles/ERT-Small-Deathsquad.yml
- Resources/Maps/Harmony/Shuttles/WizDen-ERT-Shuttles/ERT-Small-Eng.yml
- Resources/Maps/Harmony/Shuttles/WizDen-ERT-Shuttles/ERT-Small-Jani.yml
- Resources/Maps/Harmony/Shuttles/WizDen-ERT-Shuttles/ERT-Small-Med.yml
- Resources/Maps/Harmony/Shuttles/WizDen-ERT-Shuttles/ERT-Small-Sec.yml
Added 14 ERT shuttles that are available to admins on WizDen. Credit to TsjipTsjip, luckyshotpictures, and IProduceWidgets for the designs.
I intend to design more ERT shuttles for most situations but having these while I work on them allows all types of ERT to be sent without modifying existing/building new shuttles on the fly.
14 shuttles in total, here are a few:
**Changelog**
:cl:
add: Added 14 ERT shuttles, credit to TsjipTsjip, luckyshotpictures, & IProduceWidgets.
> Added Additional ERT Shuttles

- Resources/Prototypes/Harmony/Entities/Structures/Wallmounts/switch.yml
- Resources/Prototypes/Harmony/Recipes/Construction/Graphs/machines/switching.yml
- Resources/Prototypes/Harmony/Recipes/Construction/machines.yml
- Added 5 button frames to "Construction" menu: grey, exit, caution, danger, janitor
Each frame requires 1 sheet of steel.
Can be placed over any button (before or after constructing the button)
- Added lockable button to "Construction" menu
Requires 1 sheet of steel, 1 sheet of plastic, and door electronics
Access is governed by door electronics settings (set via multi tool etc)
Cannot be deconstructed if locked
Otherwise works like regular signal button
Requested by Harmony population. It should have many practical applications on shifts.
Added new entities that extend base uncraftable ones; Added recipies; Added construction graphs.
> Harmony Craftable lockable buttons and button frames

- Resources/Prototypes/Maps/bagel.yml
- Resources/Prototypes/Maps/box.yml
- Resources/Prototypes/Maps/core.yml
- Resources/Prototypes/Maps/marathon.yml
- Resources/Prototypes/Maps/meta.yml
Slightly adjusts the minimum populations of the following maps:
- **Meta:** 50 > 40
- **Box:** 50 > 40
- **Bagel:** 35 > 30
- **Marathon:** 35 > 30
- **Core:** 35 > 30
This should hopefully diversify the map pool of Harmony a bit more than at present. Basic testing has shown that these maps operate fine in our community with slightly reduced populations.
**Changelog**
:cl:
- tweak: Lowered the minimum population of several mid-pop maps.
> Adjusts minimum population of several maps.

- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Harmony/Recipes/Lathes/paper.yml
Added clipboard item to the Autolathe recipes.
Requires 0.5 wood to be printed
Requested by players who play mute characters to have a reliable source of clipboards round start.
A recipe added; Autolahe recipes list modified in the upstream file.
**Changelog**
:cl:
- add: clipboard can now be printed in Autolathe.
> Add clipboard to Autolathe recipes

- Resources/Changelog/Harmony.yml
- Resources/Locale/en-US/Harmony/changelog/changelog-window.ftl
Changelog from Harmony fork PRs are now visible in-game.
With more and more contributions it may be hard to follow what is being added or changed.
- `Resources/Changelog/Harmony.yml` -- I parsed all of our PRs and generated the changelog yaml. Many previous PRs were edited, to conform with changelog template format and show up in the data dump.
- `Resources/Locale/en-US/Harmony/changelog/changelog-window.ftl` -- Added label for the changelog.
Maintainers should check the changelog is in PR default format. Changelog collection to be automated later. For now I'll do it by running my poorly written API parser.
**Changelog**
:cl:
- add: Added "Harmony Changelog" tab to the in-game Changelogs.
> Add in-game Harmony changelog

- Resources/Prototypes/Harmony/game_presets.yml
- Resources/Prototypes/game_presets.yml
Adds Secret Nukies gamemode that admins can force.
Nukies are rare at the moment on Harmony for god knows why, something to do with the random gamemode scheduler even though the .yml looks normal. This will let admins force nukies once in a while until that's fixed plus this is nice to have regardless.
- type: gamePreset
id: SecretNukeops #For Admin Use: Runs Nukeops but shows "Secret" in lobby.
alias:
- secretnukeops
name: secret-title
description: secret-description
showInVote: false #Admin Use
rules:
- Nukeops
- SubGamemodesRule
- BasicStationEventScheduler
- MeteorSwarmScheduler
- SpaceTrafficControlEventScheduler
- BasicRoundstartVariation
> Secret Nukies Gamemode

- Resources/Locale/en-US/Harmony/guidebook/guides.ftl
- Resources/Prototypes/Guidebook/rules.yml
- Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLCrimeList.xml
- Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLRestrictedList.xml
- Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml
In-game Space Law guidebooks (all sources) edited to reflect Harmony changes to Space Law
Because it's good to have correct written Space Law IC.
- `Resources/Locale/en-US/Harmony/guidebook/guides.ftl` -- Loc string for Restricted Lists
- `Resources/Prototypes/Guidebook/rules.yml` -- Add separate restricted list guide entry, and add it to Space Law guide children
- `Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLCrimeList.xml` -- Crime list modifications
- `Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLRestrictedList.xml` -- New Restricted Areas and Items lists
- `Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml` -- Space Law 
**Changelog**
:cl:
- tweak: In-game Space Law guidebooks are now Harmony Space Law.
> Change in-game Space Law guidebooks to reflect Harmony Space Law

- Content.Client/_Harmony/RoundEnd/RoundEndNoEorgUIController.cs
- Content.Client/_Harmony/RoundEnd/RoundEndNoEorgWindow.cs
- Content.Shared/_Harmony/CCVars/HCCVars.cs
- Resources/Locale/en-US/_Harmony/round-end/round-end-no-eorg-window.ftl
Adds a popup on round end with a reminder about no EORG rules.
- Close button is timed -- enabled after 5 seconds.
- "Don't show again" checkbox works via CVar.
A lot of bwoinks are pure EORG from players who are new to the server and didn't read the rules.
This reminder, hopefully, will improve the situation and give admins time to do something other than EORG bwoinks.
- `RoundEndNoEorgUIController` subscribes to the Network Event `RoundEndMessageEvent`.
- CLIENTONLY `harmony.skip_roundend_noeorg` CCVar controls if the popup will be shown or not.
Saved to client config.
- For testing purposes, you can set `ccvar harmony.skip_roundend_noeorg false` in console to see the popup again on round end, after it was dismissed with "Don't show again" checkmark.
- …
> Add No EORG popup on round end

- Resources/Prototypes/Atmospherics/gases.yml
Frezon price/mole 0.3 -> 2
Price was nerfed upstream from 3 to 0.3 and the production got more difficult and costly.
Keeping the production change, and bumping the sale price to 2 make it still worth the time and skill investment.
We can revert this when Atmos has more things to do.
Requested by Atmos players to have fun things to do.
I personally don't see it as a major balance issue to have an ultra rich Cargo once in a while. It gives more RP possibilities and time to do it, if anything.
With this change a can of Frezon should sell for around 80k.
**Changelog**
:cl:
- tweak: Frezon selling price is changed to 2 spesos per mole.
> Unnerf the Frezon price

- Resources/Prototypes/Entities/Objects/Fun/Instruments/instruments_misc.yml
- Resources/Prototypes/_Harmony/Entities/Objects/Devices/red_phone.yml
Red phone is now an Intercom with CentComm channel.
More immersion when talking to Central Command. Proposed by Spanky.
`Resources/Prototypes/_Harmony/Entities/Objects/Devices/red_phone.yml`
- New red phone entity with components that make it an Intercom
- Also a command contraband
`Resources/Prototypes/Entities/Objects/Fun/Instruments/instruments_misc.yml`
- Changed ID of red phone to `PhoneInstrumentUpstream`
<ins>This is done to automatically remap all red phones on all maps to our version.</ins>
- Changed parent of blood-red phone and banana phone to `PhoneInstrumentUpstream`
To avoid nukies and clown having direct line to CentCom.
**In game**
**In action**
- New phone has a `[harmony intercom]` suffix for easier spawn and to distinguish from the OG version.
- If you are mapping on …
> Make red phone an Intercom with CentCom channel

- Resources/Prototypes/Roles/Jobs/Civilian/bartender.yml
- Resources/Prototypes/Roles/Jobs/Civilian/chef.yml
- Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
- Resources/Prototypes/Roles/Jobs/Civilian/mime.yml
- Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
lawyer, mime, bartender, chef, and technical assistant minimum requirements are all set to 0 hrs.
Was overlooked in initial timer change.
None of note
None
None
**Changelog**
:cl:
- fix: Fixed playtime requirements for lawyer, mime, bartender, chef, and technical assistant.
> Role timer fixes for lawyer, mime, bartender, chef, and technical assistant

- Content.Server/_Harmony/RoundEnd/RoundEndSystem.Pacified.cs
- Content.Shared/_Harmony/CCVars/HCCVars.cs
Original code by DebugOk, deltanedas, and NullWanderer for DeltaV
Available at: https://github.com/DebugOk/Delta-v/blob/master/Content.Server/DeltaV/RoundEnd/RoundEndSystem.Pacified.cs
Original PR: https://github.com/DeltaV-Station/Delta-v/pull/350
* Gives any entity that is able to harm a pacified component
* Makes explosives useless
* Makes grenades useless
* Makes flashes useless
* Breaks uplinks
Having no mechanical changes did not help with EORG.
* Requires `game.round_end_pacifist` CVar to be set to `true`
* `Content.Server/_Harmony/RoundEnd/RoundEndSystem.Pacified.cs`
https://github.com/ss14-harmony/space-station-14/pull/96 should be reverted
**Changelog**
:cl:
- add: Added anti-EORG measures.
- remove: Removed "No EORG" popup at round end.
> Anti EORG measures (round end pacifist mode)

- Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml
Bug fix
An issue was introduced by https://github.com/ss14-harmony/space-station-14/pull/61
`ghost-role-information-rules-default-solo-antagonist` is not in FTLs but referenced by several roles.
Use `ghost-role-information-antagonist-rules` instead.
> Fix Rat King Solo Antag popup

- Resources/Prototypes/_Harmony/Entities/Clothing/Belt/quivers.yml
- Resources/Prototypes/_Harmony/Entities/Mobs/raiders.yml
- Resources/Prototypes/_Harmony/Loadouts/Misc/rimworld.yml
Adds 3 weak raiders (Claymore/Mosin/Bow) and 4 regular raiders (Medic/Rifleman/Demolitionist/Sniper) to the admin spawn panel. 
I've got more things in the works but I have several local repos on several computers that don't really communicate and its annoying so I'm pushing this now and will finish everything else I have planned on another PC (Until i inevitably get bored again and start another PR on this PC but shhh)
When setting up for rimworld, it's painful to need to spawn every item manually and then give it to the character. This allows admins to just spawn preset raiders and ease admin load. 
The balance is entirely untested but it's admeme stuff.
Added a bunch of prototypes. Ideally they have randomly chosen clothing but the way random equipment loadouts work would mean a …
> Add basic raiders

- Content.IntegrationTests/Tests/Commands/SuicideCommandTests.cs
- Content.Shared/Atmos/Atmospherics.cs
Increased low pressure damage (barotrauma) from 1 to 4.
This was originally reduced on upstream via https://github.com/space-wizards/space-station-14/pull/29478 largely due to shuttle bombing and other issues. Recent changes (such as nerfs to meteors) have made this less of a problem, especially paired with Harmony’s anti shuttle bombing rule. Players being able to run around in spaced rooms and even space without protection for extended periods is unrealistic and anti-RP. Some discussion has led to the opinion that players on Harmony will be prepared to deal with a return to the old damage.
Changes one number, should be reverted if upstream changes the value or how the system works.
**Changelog**
:cl:
- tweak: Barotrauma damage has been quadrupled (to be in line with values before …
> Increase Barotrauma Damage

- .github/workflows/rsi-diff.yml
I want the action back as it's handy for posters, mapping, clothing, and other changes. Allows us to view the textures right in the PR via bot comment.
We will have run failures due to access, most likely. Same as the tagger action had. But it's worth the fix, IMO.
> Reenable Diff RSIs github action

- Content.Client/Cargo/BUI/CargoOrderConsoleBoundUserInterface.cs
- Content.Client/Cargo/UI/CargoConsoleOrderMenu.xaml
- Content.Client/Cargo/UI/CargoConsoleOrderMenu.xaml.cs
- Content.Server/Cargo/Systems/CargoSystem.Orders.cs
- Content.Shared/Cargo/BUI/CargoConsoleInterfaceState.cs
- Resources/Locale/en-US/_Harmony/cargo/cargo-console-order-component.ftl
Adds a crew list `OptionButton` to the Cargo console Order menu.
This allows to quickly fill out the `Name` field of the order. See the attached video.
If the requester name is too long or too complicated, or they left and you forgot their name while common going crazy -- it's easy to forget or type in the wrong name.
Usually, cargo techs default to their name in this field in these cases (at least I do) or even in all cases.
This QoL feature should make selecting the requesters much easier and will make the blue order slips mostly perfect for the paperwork nerds.
It might also provide an opportunity for spotting the people that are not on the manifest, if this is important for the round.
Vanilla functionality is unchanged. You can still type in anything in this field, if you want to.
- …
> Cargo QoL: Add dropdown with list of crew members to order menu

- .github/CODEOWNERS
`/Resources/Prototypes/_Harmony/Maps/` were misowned by Keld and me instead of @spanky-spanky
> Add Harmony maps to CODEOWNERS

- Resources/Prototypes/_Harmony/Entities/Mobs/Player/humanoid.yml
Adds admin spawnable prototypes of ERT roles with role time requirements.
ERT roles can carry a lot of responsibility, so having some assurance that the person taking it will have some level of competence is useful. This does not remove the default spawnable options which still do not have timers.
Adds a .yml with new prototypes that all use the originals as a parent. Modified from https://github.com/space-wizards/space-station-14/pull/29766
**Changelog**
Not player facing.
> Add ERT Role Timers

- .github/CODEOWNERS
- Add @DieselMohawk as a code owner for sprites and lobby screens.
- Includes path for upcoming migration of lobby screens
> CODEOWNERS: add DieselMohawk

- Content.Client/Cargo/UI/CargoConsoleOrderMenu.xaml.cs
Addition to #157 -- crew member list in the dropdown is now sorted alphabetically.
After testing this, alphabetical order seems to be more usable than by department order.
Added simple sorting with linq.
N/A
**Changelog**
:cl:
- tweak: Crew member list in cargo order menu is now sorted by name.
> Sort the crew members in the cargo order crew dropdown by name

- Content.Server/Chat/SuicideSystem.cs
- Content.Shared/_Harmony/CCVars/HCCVars.cs
Adds a `ic.disable_suicide` server CVar.
When `false` (default) -- no change.
When `true` -- ghosts but leaves the entity alive and SSD.
Admins wanted it.
> There aren't really a lot of scenarios (if any) where doing it wouldn't be a rulebreak and it would solve some issues if it was disabled. Keeping /ghost is fine since it keeps you alive, along with mechanical suicide methods.
~ Spanky
- `Content.Shared/_Harmony/CCVars/HCCVars.cs` -- new CVar
- `Content.Server/Chat/SuicideSystem.cs` -- subs to CVar, sets a boolean, nopes out without error at appropriate moment if set (before the suicide event raised, but after ghost event is raised)
https://github.com/user-attachments/assets/d9bc2b81-2af5-443d-b5d1-e3901c6df668
None
**Changelog**
:cl:
- tweak: Suicide console command is now disabled on …
> Add CVar to disable suicide command and ghost instead

- Resources/Prototypes/Loadouts/loadout_groups.yml
Unhide the loadout groups for breathing tools (generic, medical, sec)
Jack is cooking very pretty Vox masks that allow you to eat.
Boolean switch in three protos.
NA
**Changelog**
No need. Explanation should be on the first mask PR.
> Unhide breathing mask loadout groups

- Resources/Prototypes/Entities/Mobs/Player/guardian.yml
The holoparasite's damage has been adjusted to take longer for permakilling targets.
Holoparasites are one of the best tools for quickly round removing players, but this strength has caused numerous issues with overzealous antagonist players killing too many non-targets. The holoparasite's overall damage has also not been changed, as I think it should be indeed still be a very 
My aim of this stat change to turn holoparasite gibbing into a conscious dedicated act, instead of a quick and thoughtless one. The holoparasite's overall damage has also not been changed, as I think it should be indeed still be a very 
Resources/Prototypes/Entities/Mobs/Player/guardian.yml
Old damage - 
Blunt: 20
New damage - 
Blunt: 6
Slash: 7
Piercing: 7
This means it will take 3.33.. times longer for a …
> Holoparasite damage change.

- Content.Server/Materials/MaterialReclaimerSystem.cs
- Content.Shared/Materials/MaterialReclaimerComponent.cs
- Content.Shared/Materials/SharedMaterialReclaimerSystem.cs
- Resources/Prototypes/Entities/Structures/Machines/recycler.yml
The recycler now deals 30 (60) damage instead of gibbing you when emagged
Rules become mechanics.
Emags are incredibly common items which have so many uses it's almost kneecapping yourself NOT to buy one. Since it's one click to make the recycler into a killing machine, it results in many people being gibbed, which is against server rules.
This retains the danger of the recycler and still allows you to make it into a death trap (with more effort), but avoids situations where people would emag the recycler just because (tm) and RR 3 people
Calls TryChangeDamage instead of doing a whole bunch of gibbing stuff. Added a new property to the Recycler component to control the damage output
Logs and comments updated to reflect the change.
Currently the recycler grinds every entities (even items) …
> Recycler EMAG Rework

- Content.Server/ImmovableRod/ImmovableRodSystem.cs
- Resources/Prototypes/Entities/Objects/Fun/immovable_rod.yml
Immovable rods now deal 400 pierce damage (ignoring resistances) instead of outright gibbing you.
Being round removed by random events outside of your control is not fun.
Fixed upstream bug where the rod would delete you outright instead of gibbing you.
Rest is just yaml.
**Changelog**
:cl: Jajsha
- tweak: Immovable rods now deal massive pierce damage instead of deleting you.
> Remove rods gibbing you

- Resources/Prototypes/Catalog/Fills/Lockers/security.yml
- Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
- Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
- Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
- Resources/Prototypes/Roles/Jobs/Security/warden.yml
Security personnel now start with a disabler on them instead of in their locker.
Requested by the big man himself.
On some stations, the number of officers and the number of available disablers don't match. This ensures every security officer has their disabler.
Just YAML
**Changelog**
:cl: Jajsha
- tweak: Security personnel now start with a disabler on them instead of in their locker.
> Security roundstart disablers

- Resources/Prototypes/Species/human.yml
Makes Cat markings selectable in the loadout menu
We have cat fellas who would appreciate it.
``Resources/Prototypes/Species/human.yml`` Adds Tail Layer to character Human species and makes cat ears and tail have a marking token
**Changelog**
:cl:
- add: Made Cat Markings Accessible
> Cat Ears and Tail Support for Humans

- Resources/Prototypes/Catalog/Fills/Lockers/wardrobe_job.yml
Adds Vox tank harnesses and passenger headsets to prisoner wardrobes. Vox need a way to hold tanks more comfortably, prisoners have a right to communications. 
Space law
**Changelog**
:cl:
- tweak: Prisoner wardrobes now contain tank harnesses and passenger headsets.
> Prison Wardrobe Tweaks

- Resources/Prototypes/Catalog/Fills/Crates/fun.yml
- Resources/Prototypes/Catalog/Fills/Crates/service.yml
- Resources/Prototypes/_Harmony/Catalog/Fills/Items/toolboxes.yml
Added more ways to obtain rubber duckies
The lack of rubber duckies in space station 14 has been a disheartening sorrow of mine for too long. In my profound wisdom I am pushing this PR so that we can make space station 14 great again. 
More stuff in catalog and crates
None 👍 
**Changelog**
:cl:
- add: Added more ways to obtain rubber duckies. Ducks are now included in toy box and janitorial supplies crate cargo purchases
> Adding more ways to obtain rubber duckies

- Resources/Maps/_Harmony/Shuttles/ShuttleEvent/chemlab.yml
- Resources/Prototypes/GameRules/unknown_shuttles.yml
- Resources/Prototypes/_Harmony/GameRules/unknown_shuttles.yml
- Resources/Prototypes/_Harmony/Shuttles/shuttle_incoming_event.yml
Adds new ChemLab visiting shuttle with visiting chemist ghost role and basic chemistry lab.
I'd like to start getting a little more creative with the visiting shuttles since most of the time they end up untouched. This particular shuttle lets people learn chemistry in an environment without the pressure of keeping a medbay stocked. It can either help the station or be a non-antagonistic drug lab (no uplink chemicals provided).
New _Harmony files for shuttle events via:
`Resources/Prototypes/_Harmony/GameRules/unknown_shuttles.yml`
`Resources/Prototypes/_Harmony/Shuttles/shuttle_incoming_event.yml`
Uses parents of upstream files, which are relevant to hostile/non-hostile shuttle variants.
**Changelog**
:cl:
- add: New visiting shuttle event "ChemLab."
> ChemLab Visiting Shuttle

- Resources/Maps/_Harmony/Shuttles/ShuttleEvent/syndicatereinforcement.yml
- Resources/Prototypes/GameRules/unknown_shuttles.yml
- Resources/Prototypes/_Harmony/GameRules/unknown_shuttles.yml
- Resources/Prototypes/_Harmony/Shuttles/shuttle_incoming_event.yml
- Adds new Syndicate Reinforcement shuttle and gamerule.
- Removes Instigator ship from the unknown shuttle pool.
Part 2 of a series of new mid-round shuttles. This one aims to provide a more balanced and RP capable antagonist shuttle to replace the now removed Instigator shuttle, which has had admin consensus of being unsuited for Harmony.
The pictured shuttle spawns with a syndicate spy reinforcement and monkey agent, both of which will spawn with their own objectives. On the table is a syndicate PDA (for access), an uplink with 10TC (enough to be creative but not overpowered), and also a suspicious toolbox. Not pictured is a stack of plasma to power the P.A.C.M.A.N. generator which keeps the ship from running indefinitely, since shuttle antags can get carried away.
**Changelog**
:cl:
- …
> New Syndicate Reinforcement Shuttle + Remove Instigator

- Resources/Prototypes/_Harmony/Roles/Jobs/CentComm/official.yml
Adds new startingGear presets which can be used to clothe characters for admin use via the right-click debug menu.
Increases speed and ease of admin interaction via CC officials by allowing admins to dress characters in preferred clothing with a few button clicks rather than spawning everything. Largely not player facing, PR also serves as template for future presets.
New file in: `\Resources\Prototypes\_Harmony\Roles\Jobs\CentComm`
> CC Gear Presets

- Resources/Locale/en-US/_Harmony/station-events/events/ert-shuttles.ftl
- Resources/Maps/_Harmony/Shuttles/ShuttleEvent/ERTEngiJaniMedium.yml
- Resources/Maps/_Harmony/Shuttles/ShuttleEvent/ERTEngiSmall.yml
- Resources/Maps/_Harmony/Shuttles/ShuttleEvent/ERTJaniSmall.yml
- Resources/Maps/_Harmony/Shuttles/ShuttleEvent/ERTMedMedium.yml
- Resources/Maps/_Harmony/Shuttles/ShuttleEvent/ERTMedSecLarge.yml
- Resources/Maps/_Harmony/Shuttles/ShuttleEvent/ERTMedSmall.yml
- Resources/Maps/_Harmony/Shuttles/ShuttleEvent/ERTSecMedium.yml
- Resources/Maps/_Harmony/Shuttles/ShuttleEvent/ERTSecSmall.yml
- Resources/Prototypes/_Harmony/GameRules/ert_shuttles.yml
- Resources/Prototypes/_Harmony/GameRules/unknown_shuttles.yml
- Resources/Prototypes/_Harmony/Shuttles/shuttle_incoming_event.yml
Adds a series of new GameRules to be used by admins via addgamerule. Does not add to add to the space traffic control scheduler. Each comes with a relevant Central Command station announcement.
Popular admin request. Exponentially streamlines calling ERT so that it is no longer a chore. Sometimes it takes so long to setup ERT that the threat may be either gone, out of control, or evac may have arrived. It's now as simple as a short console command!
- Map files in `/Resources/Maps/_Harmony/Shuttles/ShuttleEvent/`
- New GameRule prototypes in `/Resources/Prototypes/_Harmony/GameRules/ert_shuttles.yml`
- New announcements in `/Resources/Locale/en-US/_Harmony/station-events/events/ert-shuttles.ftl`
- Added preloaderGrids to `/Resources/Prototypes/_Harmony/Shuttles/shuttle_incoming_event.yml` …
> ERT GameRules for Admins

- Resources/Prototypes/Entities/Objects/Specific/Chemistry/chem_bag.yml
- Resources/Prototypes/Entities/Objects/Specific/chemistry-vials.yml
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/_Harmony/Entities/Objects/Specific/Medical/healing.yml
- Resources/Prototypes/_Harmony/Recipes/Lathes/medical.yml
Added Blood packs, Vials, Circular saws and Medical HUDs to the medfab inventory
Removed combat medikits from the medfab inventory
Allowed vials to be inserted in various medical containers, like bottles (Chemistry shelves, Medical belt)
Allowed jugs to be inserted into chemistry bags.
Consistency is good. 
Recipes were most likely forgotten about over time. For instance, there is no reason for vials to not be obtainable in the same way as bottles, and for them not to be insertable in belts while bottles are.
Advanced medikits are a 2x4 inventory which takes 2x2 room, leading to situations where people fill their inventory with nested storage. Besides, it's an uplink item and should be special.
Chemistry bags being able to fit everything chemistry related BUT jugs, which would be the most …
> Medical fabricator update & whitelist tweaks

- Resources/Prototypes/GameRules/roundstart.yml
Made max nukie count 4 instead of 5
Putting this up as an option, following admin discussion and community feedback. This is not final. This might not get merged. Only time will tell.
Once again, 100% untested :) Will test once I am on a more stable PC
**Changelog**
:cl: Jajsha
- tweak: Lowered nukie max count to 4
> Lower max nukie count to 4

- Resources/Prototypes/Entities/Structures/Doors/Firelocks/firelock.yml
Grants IDs with the Security or Command access tag to open and close firelocks at will, even when in 'lockdown'.
This was limited to Engineering only. Command should have access to such a basic system on the station. 
This will also severly increase the mobility and effectiveness of Security during Nukie or Dragon incursions.
Change under `\Resources\Prototypes\Entities\Structures\Doors\Firelocks` Line 109
This shows the access of the card 
And this shows that it works
Works the same with only command
**Changelog**
:cl:
- tweak: Granted ID cards with the Command or Security access tag to open and close firelocks.
> Grant Command and Security firelock access

- Resources/Maps/_Harmony/Nonstations/listening-outpost.yml
`BoxFolderRed` named `Blank Forgery Folder C-2 S` on listening outpost introduces a test issue.
It has 20 slots, and 18 fills mapped.
`BoxFolderBase` has a chance to spawn with 0-5 papers
If the game chooses those to be more than 2
```
Failed NonGameMapsLoadableTest [32 s]
Error Message:
SERVER: 25.776s [ERRO] system.storage: Tried to StorageFill paper (491499/n491499, Paper) inside Blank Forgery Folder C-2 S (490139/n490139, BoxFolderRed) but can't. reason: No room!
```
test fails
Bug fix
Removed entities  765, 748, and 721 (a cargo invoice, a cargo manifest, and a forensic report) from fill.
> Fix NonGameMapsLoadableTest for Listening Outpost

- Resources/Prototypes/_Harmony/Entities/Clothing/Masks/masks.yml
Removes WhitelistChameleon tag from vox-specific masks.
Bug fix. It was a way to wear chameleon mask without any mask showing up in game for non-vox users.
Adds Tag component with empty array of tags to overwrite inherited tags (WhitelistChameleon, and HamsterWearable in case of enfocer mask)
N/A
**Changelog**
> Remove whitelist chameleon tag from vox-specific masks

- Resources/Prototypes/Entities/Objects/Tools/access_configurator.yml
- Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml
Added various items to the aghost bag, all of which were specifically requested by admins.
Made the access configurator admins spawn with have an ID card inside by default
Allows admins to be able to handle some things more effectively
- Omnitool, holofan and welder added to allow admins to fix things without spawning themselves tools every time
- Anomaly scanner and CHIMP added for better handling of anomalies inside players
- Bluespace beaker and syringe for better reagent handling
- Emag and cenctomm stamp for fax machine stuff (You need to emag the fax machine to send things to the nukie planet)
Just YAML
**Changelog**
Not player facing
> Add items to the aghost bag

- Resources/Prototypes/Roles/Jobs/Civilian/service_worker.yml
_Please be patient, this is my first ever PR._
Gives service worker Hydroponics Access.
The service worker should be able to assist in all aspects of food service, not strictly the bar and kitchen. Botany is one of the lesser-populated service roles despite it's essential role to chemistry and kitchen and this PR allows service worker players to fill in for staff without disrupting chemistry or kitchen. 
Added Hydroponics access to service_worker.yml and removed Hydroponics as extended access.
**Changelog**
:cl: Anno_Midi
- tweak: Gave service worker hydroponics access
> Give Service Worker Hydroponics access

- Content.Shared/Ninja/Components/StunProviderComponent.cs
Reduced the stun timer on the stun component to match the flash
The stun is likely intended to be for disengagement and disarming crew, but currently it's used to instantly stun cuff or kill people. It's a VERY aggressive tool for a supposedly sneaky antagonist.
`Content.Shared/Ninja/Components/StunProviderComponent.cs` Stun time component had timer reduced
**Changelog**
:cl:
- tweak: Ninja Stun Reduced to fit Flash stun time.
> Ninja Glove Stun Reduced To Match Flash

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/Entities/Mobs/NPCs/carp.yml
- Resources/Prototypes/Entities/Mobs/NPCs/slimes.yml
Removed the ghost role raffle from slimes, spiders, and the dragon's carps.
This means they can be played as almost instantly after they spawn.
With the port of the vent critter rework from DeltaV, security is able to know the general area where the spiders and slimes are going to appear before they even spawn. This means there is a high chance for security to kill all of them before the raffle finishes which is sad for ghosts.
As for the dragon's carps, there are usually either over 10 in which case having a raffle is completely unnecessary or they are being spawn camped which leads to the same problem as slimes and spiders.
Pictured: blue slime, green slime, yellow slime, tarantula, clown spider, dragonbrood carp
**Changelog**
:cl:
- tweak: Removed the ghost role raffle from slimes.
- …
> Remove the raffle from slimes, spiders, and carps.

- Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
Changed the rat king's ghost role description.
Confused players. Rat kings are antagonists and shouldn't be cooperating with the station.
**Changelog**
Not player facing
> Change description of rat king

- Content.Server/Maps/GameMapPrototype.cs
Makes the station start un-rotated and aligned with map rotation.
The station being randomly rotated causes unnecessary confusion for salvagers and others outside of the station, and even admins to a minor extent while using a mass scanner. Round start rotation and offset was added to dissuade contributors from using absolute position values. This was rarely an issue for salvagers when the reclaimer existed, but now causes problems that I would never describe as a skill issue. PR only changes rotation and not starting offset (station will not be at 0,0), and station can still be moved off axis if the anchor is disabled.
`Content.Server/Maps/GameMapPrototype.cs` RandomRotation changed from true to false.
**Changelog**
:cl:
- tweak: The station will now start rotationally aligned to space.
> Disable Default Station Rotation

- Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
- Resources/Prototypes/Roles/Jobs/Command/captain.yml
- Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
- Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
- Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
- Resources/Prototypes/Roles/Jobs/Science/borg.yml
- Resources/Prototypes/Roles/Jobs/Science/research_director.yml
- Resources/Prototypes/Roles/Jobs/Security/detective.yml
- Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
- Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
- Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
- Resources/Prototypes/Roles/Jobs/Security/warden.yml
Increased job requirements of most command jobs to 8 hours in department and 12 hours of overall playtime. Minor other changes, advise reading files.
General overall community/staff sentiment to make command more restrictive to play, especially security. Numbers based on staff discussion and reinforced by in-game polls. Aim is to increase command competence and prevent new and/or malicious players from rushing to roles with power.
Multiple job files changed in `Resources/Prototypes/Roles/Jobs/`
**Changelog**
:cl:
- tweak: Increased role timers for command and security.
> Adjust Role Timers

- Content.IntegrationTests/Tests/PostMapInitTest.cs
Reorganizes Harmony's maps to the top of their list in `PostMapInitTest.cs` for cleanliness.
The maps were starting to get jumbled a bit with upstream merges and this should keep them all clean and prevent future merge conflicts.
Shifted lines of code in `PostMapInitTest.cs`
> Reorganize PostMapInitTest.cs

- Resources/Prototypes/Maps/Pools/default.yml
Removes Loop from rotation.
Over time there has been a general dislike of Loop in Harmony's MRP environment and a desire to remove it from rotation. Shifts on it often have increased levels of LRP activity and undesired chaos. I've waited a few months to see if it got significant improvements but it hasn't, and the mapper is no longer in our Discord to receive feedback.
**Changelog**
:cl:
- remove: Removed Loop from rotation.
> Remove Loop from Rotation

- Content.Client/Materials/UI/MaterialDisplay.xaml.cs
It's annoying having to spam click 10 stacks to get a full stack, which everyone uses, so instead let's make it one click away.
Nice QoL for anyone who needs to remove materials, mostly for cargo.
Simply added 30 to the ui eject array.
https://youtu.be/TmXRu0ekpHE
**Changelog**
:cl:
- tweak: Lathes/Fabs can now eject full 30 stacks
> Allow lathes/fab to eject full 30 stacks

- Resources/Prototypes/Catalog/spellbook_catalog.yml
- Resources/Prototypes/secret_weights.yml
Wizards are way too common for what is supposed to be the rarest antag. I believe the best solution is to remove the gamemode dedicated to wizards. Wizards often purchase the "event" spells which cause mass chaos and admin issues as well. This PR removes event spells, and reduces the likelihood of seeing wizards. PR also removes kessler cause I thought it was removed awhile ago, and it was supposed to be gone. 
Event spells are very disruptive and cause admin issue. Also those spells are a lot more "memey" and don't seem to fit Harmony too well. Wizards are also too common.
**Changelog**
:cl:
- remove: Removed event spells from the wizard.
- tweak: Reduced the likelihood of wizards appearing.
> Remove event spells and reduce wizard chances of rolling

- Resources/Prototypes/Objectives/objectiveGroups.yml
- Resources/Prototypes/Objectives/traitor.yml
- Resources/Prototypes/_Harmony/Objectives/traitor.yml
See title, "survive" is at the same difficulty/rarity as current "Escape" is (1.3 difficulty, 0.6 weight) while "Escape" has been changed to be less common (difficulty stays at 1.3, weight is now 0.4, instead of 1)
Community sentiment is that this would overall be a good change, as seen by the poll below. Personally, I think this objective overly discourages traitors to have any mid-round conflict with security, causing issues such as traitors waiting to do their objectives extremely close to evac, giving security nothing to do for the majority of a traitors shift. (also, as far as I'm aware antag activity on the evac shuttle is something that should be discouraged)
Adds:
Resources/Prototypes/_Harmony/Objectives/traitor.yml
Changes:
Resources/Prototypes/Objectives/objectiveGroups.yml …
> Adds "Survive" Objective to traitors, makes "Escape to centcomm alive and unrestrained" more rare.

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
I reverted [#34890](https://github.com/space-wizards/space-station-14/pull/34890), changing disablers back to their orignal state
__"Disablers are actually awful. Probably the worst performing I've seen them across Space Station history."_ - keronshb_
while disabler smgs and disablers have been under utilized for quite a while, I think that making them better ranged stun batons wasnt the answer, and while the disablers does need changes, this is just not it.
Edited Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml - Reverted Disabler Changes
Edited Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml - Reverted Disabler Changes
**Changelog**
:cl:
- tweak: Reverted the disabler buff, rejoice.
> Reverts disabler buff

- Resources/Audio/_Harmony/Lobby/attributions.yml
- Resources/Prototypes/SoundCollections/lobby.yml
Adds new lobby track "Dropzone," by Qwesta. Originally created for RMC and included in PR https://github.com/RMC-14/RMC-14/pull/6021
As soon as I heard this I wanted it in Harmony. It works beautifully for RMC but also has that Nukie feel and should be another step towards slowly shifting to unique lobby music.
[Link](https://discord.com/channels/1168210010233376858/1168217282988757116/1311095405647495401) to the song in the RMC discord.
**Changelog**
:cl:
- add: New lobby song Dropzone by Qwesta.
> Add New Lobby Track "Dropzone"

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/SpeedLoaders/magnum.yml
Totally didnt swipe this from someone else. Changes Speedloaders to be 1x1.
Makes Revolvers more viable, currently they arent a good weapon for people with trash aim.
Edited Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/SpeedLoaders/magnum.yml - Adjusted size of magnum ammo
**Changelog**
:cl:
- tweak: Changed Magnum Speedloaders to be 1x1 instead of 1x2
> Magnum Speedloaders are now 1x1 (My totally original idea)

- Resources/Prototypes/Catalog/uplink_catalog.yml
- Resources/Prototypes/_Harmony/Catalog/uplink_catalog.yml
After hearing Gray wanting this and talking with someone people about the idea I decided why not try to do this. So I added the raid suit to traitor uplinks.
The raid suits were meant for use by Nukies, but because of the lack of space protection basically make it useless to them. It would be far more useful to normal traitors as spacing is less of a issue for them. Additionally as it would be access by normal traitors increased it's cost to 12TC to match the Elite and Jugg suits.
On recommendation of Bosko made a duplicate in _Harmony uplink catalog specifically for traitors, increased the cost to 12TC, and added ability for it to be discounted to 7TC. The normal Nukie one remands unchanged
https://youtu.be/DljW4h0rQkI
**Changelog**
:cl:
- add: Traitors can now buy raid suits at 12TC.
> Added raid suit to traitor's uplink

- Resources/Prototypes/Entities/Clothing/Belt/belts.yml
- Gives the Bandolier actual Storage Slots
Makes them "funner" to use
Resources/Prototypes/Entities/Clothing/Belt/belts.yml -- Updates the Bandolier
**Changelog**
:cl:
- tweak: Gives the Bandolier actual Storage Slots
> Gives the Bandolier Actual Belt Storage Slots for Shotgun Shells

- Resources/Prototypes/Loadouts/loadout_groups.yml
Trinket comments now properly label every change as a harmony change.
> Fix trinket comments

- Content.Server/Cluwne/CluwneSystem.cs
This PR makes a simple change to make cluwnes revivable as per discussions. The request was made after a round where 5 or more people were rendered completely round removed after being made into cluwnes, which does not line up with other transmutation spells like carp and bread. 
It was discussed ingame and in the Discord that cluwnes having 300 genetic is extremely undesirable and should be changed. This fact was agreed upon by the community and admins that this change needs to happen.
This affects both the cluwne spell for wizards and the admin smite
N/A
**Changelog**
:cl:
- tweak: Being cluwned is no longer round removal
> Make cluwnes revivable

- Resources/Prototypes/Entities/Clothing/Belt/belts.yml
- Energy Cartridges Can Now Fit in Sec Belts
I forgor
Resources/Prototypes/Entities/Clothing/Belt/belts.yml -- Adds energy cartridges to the secbelt whitelist
**Changelog**
:cl:
- tweak: Energy Cartridges Can Now Fit in Sec Belts
> Energy Cartridges Can Now Fit in Sec Belts

- Content.Shared/SprayPainter/Components/SprayPainterComponent.cs
- Resources/Prototypes/Entities/Objects/Tools/spray_painter.yml
turned the time to color pipes from 1 -> 0
It encourages atmos techs to color their pipes since it no longer takes forever, at the cost of their ears
Content.Shared/SprayPainter/Components/SprayPainterComponent.cs - 1 to 0
https://github.com/user-attachments/assets/86756a5e-1c47-426f-af97-2a27980aafd1
**Changelog**
:cl:
- tweak: Spray painters now instantly color pipes
> Removes pipe coloring cooldown from spray painter

- Resources/Prototypes/Entities/Objects/Specific/syndicate.yml
- Resources/Prototypes/Roles/Antags/nukeops.yml
- Removes the starting blood-red from nuclear operatives and lone op
- Increases the nukie and lone op uplink by 5 TC
This change encourages Nuclear Operatives (Just the operatives, not agent or commander) to try different armor types instead of just the blood-red they start with. This is balanced by giving everyone 5 more TC (Totaling at 20 across the team), so the 16 that has to be spent for a normal blood-red is canceled out.
Resources/Prototypes/Entities/Objects/Specific/syndicate.yml -- Updates Nukie Uplink Amounts
Resources/Prototypes/Roles/Antags/nukeops.yml -- Comments out round-start Blood-Reds from Nuclear Operatives
**Changelog**
:cl:
- tweak: All Nuclear Operative Uplinks Get an Extra 5 TC
- tweak: Nuclear Operatives and Lone Ops No Longer Start with Blood-Reds
> Increases uplink TC amount and Removes round-start Blood-Reds from Nuclear Operatives

- Resources/Locale/en-US/_CD/traits/traits.ftl
- Resources/Prototypes/Entities/Mobs/Player/clone.yml
- Resources/Prototypes/Traits/quirks.yml
- Resources/Prototypes/_CD/Traits/categories.yml
- Resources/Prototypes/_CD/Traits/traits.yml
Added two new alcohol theme traits the very lightweight and heavyweight traits. Originally from Cosmic Drift [#511](https://github.com/cosmatic-drift-14/cosmatic-drift/pull/511)
Added a new traits categories for the three alcohol traits.
very lightweight make you 4x booze strength
Heavyweight make you .5x booze strength
**Changelog**
:cl:
- add: Added two new alcohol theme traits
> Ported Very Lightweight and Heavyweight drunk traits from Cosmic Drifts

- Resources/Prototypes/Catalog/VendingMachines/Inventories/engivend.yml
Added two floodlights to the engi-vend.
Engineering could benefit from an additional, readily accessible light source. Flood lights become available later, but this should help relieve early-round annoyance at breaches. I've only provided two, as batteries are rechargeable and floodlights should feel like a limited resource.
Added Floodlight: 2 to Resources/Prototypes/Catalog/VendingMachines/Inventories/engivend.yml.
There are no breaking changes!
> Floodlights in Engi-vend

- Resources/Prototypes/Catalog/uplink_catalog.yml
Title. 
Pretty thoroughly dicussed before so maybe I shouldn't write 50 paragraphs here, but the biggest complaint about the noct hypopen combo is the actual chem in itself and how uncounterable it is compared to other methods.
The hypopen has very healthy utility and still requires a fair amount of prep to be useful so I don't think it should be priced high just because another item exists which makes it extremely good. 
This doesn't actually increase or decrease the total cost of the kit, just redistributes the costs of the invididual items.
literally 4 line changes
**Changelog**
:cl:
- tweak: Buffed hypopen price to 4 TC, nerfed nocturine price to 8 TC
> The Noctening - Increases nocturine price, decreases hypopen price

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Mice Now Deal One Blunt Damage When Thrown
- They also take five blunt on impact
Did a poll for it. People want it.
Resources/Prototypes/Entities/Mobs/NPCs/animals.yml -- Adds damage values
**Changelog**
:cl:
- tweak: Mice Now Deal One Blunt Damage When Thrown
- tweak: Mice take five blunt damage on Impact when Thrown
> Mice Now Deal Damage one Blunt Damage When Thrown

- Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml
- Adds the minijetpack to the Salvage Specialist Locker
- Removes the fire extinguisher from the Salvage Specialist Locker
In the end, Salvage is just going to steal the ones from EVA by either breaking in, bothering the AI, or just waltzing in and grabbing them. They might as well just start with them so the EVA jetpacks are used in actual emergencies
Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml -- Removes the fire extinguisher and replaces it with minijetpacks
**Changelog**
:cl:
- add: Added Mini Jetpacks to Salvage Lockers
- remove: Removed Fire Extinguishers from Salvage Lockers
> Adds Mini Jetpacks to the Slavage Specialist Lockers

- Resources/Prototypes/Entities/Clothing/Hands/gloves.yml
Adds 10 structural damage to the QM's Knuckledusters, allowing them to be used as a pickaxe for mining.
The flavourful feel of being able to break open rocks with your hands is really cool.
The dusters have an attack rate of 1.5.
I ran a series of tests with the dusters versus Uplink items known for being good at breaking things - the Energy Sword and the Suspicious Toolbox. Ultimately, I felt 10 felt the best when breaking rocks while not approaching the esword, and being on equal footing to the toolbox.
> --10 STRUCT--
> Asteroid: 3 Punches (~2 seconds)
> Door: 40 Punches (~26.6 seconds)
> Caps Locker: 19 Punches (~12.6 seconds)
> Secure Crate: 19 Punches (~12.6 seconds)
> Regular Window: 3 Punches (~2 seconds)
> Reinforced Window: 17 punches (~11.3)
> plasma window: 4 punches (~2.6 …
> Adds structural damage to the QM Knuckledusters

- .github/labeler.yml
- .github/workflows/labeler-pr.yml
- Labeller now uses `Changes: C#` instead of `Changes: No C#`
- Labeller now ignores all PRs with a maintenance tag
- Labeller will now remove labels if a change that was previously done is removed (e.g. PR was accidentally made with the changes of a previous PR and owner has removed them after)
- Labeller automatically adds a maintenance label to all PRs that start with 'Upstream' or 'Changelog'
I personally think that these changes would be make the labeller much simpler and less annoying to use than the current method where I need to constantly add or remove tags on maintenance PRs
> Labeller tweaks

- Resources/Maps/_Harmony/Shuttles/cargo_eclipse.yml
- Resources/Maps/_Harmony/eclipse.yml
Added Silo to R&D and Turrets to Armory, vault, security dock and AI core. Removed distortion from the Eclipse Cargo Shuttle horn and gave it's activation button a description.
Turrets were added in preperation for their upstream fix. Silo was added to meet current mapping standards.
Distortion was a feature of the bananium horn that made it more clowny, removed to make the cargo shuttle horn a regular vehicle horn.
**Changelog**
:cl:
- add: Added Turrets and material Silo to Eclipse Starport
> Eclipse update 1.3.1 Turrets and Silos

- Resources/Prototypes/Entities/Objects/Devices/pda.yml
Adds AstroNav as a preinstalled cartridge to the Quartermaster's PDA, allowing them to look at coordinates at round-start
Command parity. The other Heads of Department with PDA cartridges have them preinstalled, and while that is necessary for the CMO the HoS sets the precedent that cartridges for specialized jobs under them are still preinstalled with the Detective's Doorlogs.
The QM starts with an AstroNav cartridge in their locker, and frequently installs it anyway. This simply removes uneccesary friction and prevents newer QMs from being noob-trapped when lost in space thinking they would have coordinates available to them.
This also lets the QM aid newer salvagers better even on station, as they can quickly call out the cargo bay's coordinates now.
Adds the CartridgeLoader type to …
> Adds AstroNav to QM PDA

- .github/CODEOWNERS
Adds @raccoonio (tanuko on Discord) to CODEOWNERS as a new mapping lead. Retains my codeownership for review assistance.
> CODEOWNERS Update (tanuko)

- Content.Shared/_Harmony/BloodBrothers/Components/InitialBloodBrotherComponent.cs
- Resources/Locale/en-US/_Harmony/prototypes/roles/antags.ftl
- Resources/Prototypes/_Harmony/Roles/Antags/bloodbrother.yml
See title
Some players may want to be possible to convert into blood brothers while also not wanting to be the initial blood brother due to lore reason or even personal preference.
Added a second antag prototype that is *not* given out and replaced the old blood brother preference from the convertible check to the new preference.
**Changelog**
:cl:
- tweak: The blood brother antag selection preference has been split off into the initial and converted preference.
> Separate blood brother preference between initial and convertible

- Resources/Locale/en-US/_Harmony/store/uplink-catalog.ftl
- Resources/Prototypes/_Harmony/Catalog/uplink_catalog.yml
- Resources/Prototypes/_Harmony/Entities/Objects/Weapons/Bombs/pizzabombbox.yml
Split the Pizza Bomb item uplink listing in two, limited the original to be unable to spawn in surplus crates, limited the new one to be only available from surplus crates. The new one spawns inside a syndicate crate that clearly marks it as a bomb, and not pizza.
This is a direct responce to #726, i am aware of three times agents have detonated their surplus crate due to the pizza bomb. That is less than ideal.
Sadly no new media, will make a new pr or update here if new media (pizza delivery bag) becomes available.
None.
**Changelog**
:cl:
- add: a new listing to the syndicate uplink for a pizza bomb in a (clearly labled box, unable to be purchased, only available from surplus crates
- remove: the pizza bomb (without a box) from the surplus crate loot pool.
> Pizza bomb box

- Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml
- Resources/Prototypes/Entities/Structures/Doors/Airlocks/highsec.yml
- Resources/Prototypes/Entities/Structures/Doors/MaterialDoors/material_doors.yml
- Resources/Prototypes/Entities/Structures/Doors/Shutter/shutters.yml
- Doors No Longer Connect to Walls
An artistic change suggested by one of our project managers.
Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml -- Removes Icon Smoothing Component
Resources/Prototypes/Entities/Structures/Doors/Airlocks/highsec.yml -- Removes Icon Smoothing Component
Resources/Prototypes/Entities/Structures/Doors/MaterialDoors/material_doors.yml -- Removes Icon Smoothing Component
Resources/Prototypes/Entities/Structures/Doors/Shutter/shutters.yml -- Removes Icon Smoothing Component
**Changelog**
:cl:
- tweak: Made doors no longer connect to walls
> Doors No Longer Connect to Walls

- Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
PDAs no longer spawn twice on salvage specialists.
Whoops
Removed the default salvage PDA loadout item. The seniority PDA is now the only PDA.
**Changelog**
Not player facing
> Fix salvage specialists spawning with 2 PDAs

- Resources/Locale/en-US/store/uplink-catalog.ftl
- Resources/Prototypes/Catalog/Fills/Backpacks/duffelbag.yml
slight oversight on my part when making the gun, forgot to add the mags to the ammo bundle
seems logical since nukies have to spend more TC otherwise
changes uplink-catalog.ftl with harmony comments
changes ammo bundle description and adds DMR magazines to ammo bundle fill prototype in duffelbag.yml in upstream namespace, adds harmony comment
**Changelog**
> Adds DMR ammo to ammo bundle

- Resources/Prototypes/Catalog/Fills/Lockers/security.yml
Added binoculars to LockerWardenFilledHardsuit prototype where it was previously missing.
The Warden is supposed to get binoculars, they are part of the Warden's kit. But for some reason only the regular locker prototype has binoculars in them, and not the hardsuit filled locker. This was certainly an oversight and not intentional.
**Upstream Files**
Resources/Prototypes/Catalog/Fills/Lockers/security.yml -- Adds binoculars to the contents of LockerWardenFilledHardsuit
Before
After
**Changelog**
> Adds binoculars to all Warden lockers

- Resources/Locale/en-US/_Goobstation/bingle/bingle.ftl
- Resources/Prototypes/_Goobstation/Gamerules/bingleEvent.yml
Removes the Central Command annoucement that happens when AddGameRule BingleSpawn runs, and the bingle ghost role is spawned.
Very few antagonists announce their presence, especially ones that start as weak as a single bingle + its pit. Even major antagonists (non-ninja Dragons, Lone Ops, Wizards) either don't announce their presence, or its a choice for them via an announcement console. The announcement itself also felt not quite right for a MRP enviroment. A pole was ran to gauge interest in a new, more MRP-feeling message - but instead people suggested removing it to make the discovery of Bingles on station a bit more exciting.
This also gives other antags an excuse to be the boy who cried bingle, such as listening post faking a bingle callout that won't be meta'd by people seeing no …
> Bingles No Longer Announce Their Presence

- Resources/Prototypes/_Harmony/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
lowers hushpup firerate to 1.5
makes hushpup spread 40% higher
admins have let me know the hushpup is too much of a must buy, so i will be doing something about it
i wanted to keep the hushpup at the same price while making it less of a must buy for traitors, now you HAVE to barrel stuff people with it to instantly kill them, and it should be more punishing to miss your shots.
if this isnt enough then i will probably nerf it AGAIN or increase the price and revert the buff.
changes to weapons/guns/shotguns/shotguns.yml in harmony namespace
media soon
**Changelog**
:cl:
- tweak: Nerfed hushpup firerate and spread
> nerfs hushpup

- Resources/Locale/en-US/_Harmony/store/uplink-catalog.ftl
fixes grammar in pizza bomb description and clarifies that it is infact not a grenade
pizza bomb got changed a while ago to no longer be throwable and explodes almost instantly upon opening, this should probably be clarified so people dont kill themselves with it
also fixes grammar because it never got touched for some reason?
changes uplink-catalog.ftl in harmony namespace
**Changelog**
:cl:
- tweak: Tweaked pizza box description to be less ambiguous
> Fixes pizza bomb description

- Resources/Prototypes/Guidebook/species.yml
- Resources/Prototypes/_Harmony/Guidebook/species.yml
- Resources/ServerInfo/Guidebook/Mobs/Species.xml
- Resources/ServerInfo/_Harmony/Guidebook/Mobs/Avali.xml
Adds guidebook entry for Avali. I will try and maintain it as changes are made.
Resolves https://github.com/ss14-harmony/ss14-harmony/issues/938
modifies Guidebook/species.yml in upstream namespace, adds harmony comment
modifies Guidebook/Mobs/Species.xml in upstream namespace, adds harmony comments
adds Guidebook/Mobs/avali.xml in harmony namespace
**Changelog**
:cl:
- add: Added guidebook entry for Avali
> Guidebook entry for Avali

- Resources/Locale/en-US/_Harmony/administration/antag.ftl
- Resources/Locale/en-US/_Harmony/game-ticking/game-presets/preset-bloodbrother.ftl
- Resources/Locale/en-US/_Harmony/guidebook/guides.ftl
- Resources/Locale/en-US/_Harmony/mind/role-types.ftl
- Resources/Locale/en-US/_Harmony/prototypes/roles/antags.ftl
- Resources/Prototypes/_Harmony/Actions/blood_brothers.yml
- Resources/Prototypes/_Harmony/Objectives/bloodbrother.yml
- Resources/ServerInfo/Guidebook/Antagonist/Antagonists.xml
- Resources/ServerInfo/_Harmony/Guidebook/Antagonist/BloodBrothers.xml
Renames the antagonist introduced in https://github.com/ss14-harmony/ss14-harmony/pull/638
This is a less intense version of https://github.com/ss14-harmony/ss14-harmony/pull/864, unlike that one this one only changes the strings (player facing stuff)
See PR #864
Changed all instance of blood brother to blood bound in ftl files, yaml descriptions, and guidebook xmls
Added a missing comment to Resources/ServerInfo/Guidebook/Antagonist/Antagonists.xml for the BB line.
See PR #864
**Changelog**
:cl:
- tweak: Blood Brother has been renamed to Blood Bound.
> Rename Blood Brother to Blood Bound Lite (Player Facing Only)

- Resources/Prototypes/Catalog/uplink_catalog.yml
removes Estoc DMR from nukie and traitor uplinks
It's bloat since we currently have two DMR options and some admins have voiced their opinion that they would rather have our homemade DMR instead of the upstream one.
comments out uplink option in uplink_catalog.yml in harmony namespace adds harmony comments
picture an uplink without the estoc in it
**Changelog**
:cl:
- remove: Removed the Estoc DMR from the uplink
> removes Estoc DMR from uplink

- Resources/Prototypes/Catalog/Cargo/cargo_armory.yml
fixes incorrect sprite path, now the rifle crate uses our lecter sprite
wrong lecter sprite
Changed sprite path in cargo_armory.yml in upstream namespace, added harmony comment
**Changelog**
:cl:
- fix: Fixed upstream lecter sprite appearing in the rifle crate order
> fixes wrong lecter sprite on request computer

- Content.Server/StationEvents/Events/AlertLevelInterceptionRule.cs
- Content.Server/_Harmony/StationEvents/Components/EmptyRuleComponent.cs
- Content.Server/_Harmony/StationEvents/Events/EmptyRule.cs
- Resources/Locale/en-US/_Harmony/station-events/events/harmony-extended.ftl
- Resources/Prototypes/_Harmony/GameRules/roundstart.yml
- Resources/Prototypes/game_presets.yml
Adds an announcement to the extended preset which automatically plays after 25 minutes.
Discussion about this has been done to death about 100 times by now, so I am not going to write too much here as you can look it up in the following thread.
I will freely discuss things in the comments of this PR though.
Link to discussion:
https://discord.com/channels/1139716325627932682/1341424935788351630
To boil it down to a basic level, extended is in a state where some players feel as if the odds of extended rolling should be reduced while another would like to keep extended the way it is (generalizing here). This may or may not please both sides but it should serve to stem some frustration from players feeling like they've wasted their time or picked the wrong role for a greenshift.
added …
> Adds announcement to inform of Extended rolling

- Content.Server/GameTicking/GameTicker.Player.cs
- Content.Server/_Harmony/JoinQueue/JoinQueueManager.cs
- Resources/Locale/en-US/_Harmony/queue/queue.ftl
When a player joins the queue, the admin message will now say "Player {player} joined the queue. ({$number} in queue)"
The message that a player has joined the game will now only happen after the player has reached the end of the queue and is actually in-game
Admin tools are always good
**Changelog**
> Improve queue admin logging

- Resources/Prototypes/Entities/Objects/Fun/bike_horn.yml
This PR makes the bananium horn have a 1.5 second delay.
The sound is very obnoxious
**Changelog**
:cl:
- tweak: The use delay for the bananium horn has been increased to 1.5 seconds.
> Add a delay to the bananium

- Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
The vulps and reptilians no longer get errors as their head.
Also disabled corgi wearing for those hardsuits because yeah.
**Changelog**
:cl:
- fix: Hardsuit helmets will no longer show up as error sprites for reptilians and vulpkanins.
- remove: More hardsuits with custom sprites are no longer wearable by smart corgis.
> Fix reptilian and vulp hardsuit helmets being errors

- Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
- Resources/Prototypes/Entities/Clothing/OuterClothing/bio.yml
- Resources/Prototypes/Entities/Clothing/OuterClothing/suits.yml
Putting on a space suit will no longer hide/delete the tail of lizard players
1. It perturbs me deeply that big lizard tails disappear when putting on a space suit.
2. Maintaining lizard specific versions of suit sprites is not something I'm interested in spending effort on.
**Upstream Files**
Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml -- Comments out hiding tails
Resources/Prototypes/Entities/Clothing/OuterClothing/bio.yml -- Comments out hiding tails
Resources/Prototypes/Entities/Clothing/OuterClothing/suits.yml -- Comments out hiding tails
**Changelog**
> Space suits no longer hide lizard tails

- Resources/Prototypes/Catalog/uplink_catalog.yml
Adds the elite suit back for traitor uplinks at 12 TC.
As per one of our Curators:
_"Originally, the Elite Hardsuit was removed under the reasoning of bloat by upstream. To which I find arguable enough to atleast want to fight back against and see if Curators will approve/disapprove._
_As of currently, heat-weak species such as Diona or Moths do not have a good way to be both space immune and have solid heat-res during active engagements and to that regard I find that the elite-hardsuit fills this niche. (If they are willing to spend the TC.) While also giving back traitors of all variety, the pricey-suit back into their uplinks if they're willing to spend their money on it._"
I agree with their take and I think that the removal of the elite suit took options away from traitors and …
> Adds elite suit to traitor uplink

- Resources/ServerInfo/_Harmony/Guidebook/ServerRules/HarmonyRules/HarmonyR6.xml
Reverts ss14-harmony/ss14-harmony#1043
The change was requested to be reverted by the admin team
> Revert "Clarified EORG rules"
