ss14-harmony/ss14-harmony

Resources/Prototypes/Harmony/Entities/Clothing/Neck/pins.yml, Resources/Prototypes/Harmony/Loadlouts/Miscellaneous/trinkets.yml, Resources/Prototypes/Loadouts/loadout_groups.yml
Remove all harmony pin stuff to see if that will solve the build issues
=> Removed all custom pin code

Resources/Maps/Harmony/Shuttles/genesis.yml, Resources/Maps/Harmony/Shuttles/graniteflea.yml
Adding additional shuttles by Spanky. This is something of a test to make sure it's easy, convenient, and non-disruptive to add new shuttles for things like ERT.
=> Adding two new shuttles to load in by spanky

Resources/Maps/Harmony/Shuttles/NT-Genesis.yml, Resources/Maps/Harmony/Shuttles/NT-Graniteflea-CC.yml, Resources/Maps/Harmony/Shuttles/NT-Graniteflea.yml, Resources/Maps/Harmony/Shuttles/NT-Saviour.yml, Resources/Maps/Harmony/Shuttles/NT-Torus.yml
Got a more refined set of shuttles from Spanky. These are only meant to use used or spawned in via admin commands at this time. Shouldn't affect balance or the like as such. 
Most are ERT ships or similar.
=> Added more solid versions of the shuttles from feedback.

Resources/Maps/Harmony/Shuttles/NT-Genesis.yml, Resources/Maps/Harmony/Shuttles/NT-Graniteflea-CC.yml, Resources/Maps/Harmony/Shuttles/NT-Graniteflea.yml, Resources/Maps/Harmony/Shuttles/NT-Saviour-Freelance.yml, Resources/Maps/Harmony/Shuttles/NT-Torus.yml
Final tweaks on the shuttles Spanky made for Harmony. Best practices and stability changes via feedback from other mappers.
=> Final touches on the shuttles based on feedback from WizDen mappers.

.gitmodules
Add missing line to .gitmodules
=> fixed missing line

Content.Client/Verbs/VerbSystem.cs, Content.Server/Shuttles/Systems/ArrivalsSystem.cs, Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs, Content.Shared/Shuttles/Components/FTLSmashImmuneComponent.cs, Content.Shared/Shuttles/Components/NoFTLComponent.cs, Resources/Prototypes/Entities/Effects/puddle.yml, Resources/Prototypes/Entities/Markers/shuttle.yml, Resources/Prototypes/Entities/Mobs/Player/observer.yml, Resources/Prototypes/Entities/Mobs/Player/silicon.yml, Resources/Prototypes/Entities/Structures/Wallmounts/surveillance_camera.yml, Resources/Prototypes/Recipes/Lathes/robotics.yml, Resources/Prototypes/Recipes/Lathes/security.yml
=> Upstream20240912 night

Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml
Changes Rat King to solo antag
Lilten said so
**Changelog**
=> Rat King Solo Antag Status

Resources/Changelog/Harmony.yml
=> Changelog update

Content.Shared/Atmos/Atmospherics.cs, Resources/Changelog/Changelog.yml, Resources/Maps/Harmony/Shuttles/deathsquad-medium.yml, Resources/Prototypes/Atmospherics/gases.yml, Resources/Prototypes/Entities/Objects/Misc/pen.yml
Upstream merge for September 26, 2024
=> Upstream9262024

Resources/Changelog/Harmony.yml
=> Changelog20240927

Resources/clientCommandPerms.yml
`fuckrules` removed from available commands
We love rules!
=> Disable fuckrules command

Content.Client/Inventory/StrippableBoundUserInterface.cs, Content.Client/UserInterface/Systems/Actions/ActionUIController.cs, Content.Client/UserInterface/Systems/Actions/Controls/ActionButtonContainer.cs, Content.Shared/Hands/Components/HandsComponent.cs, Content.Shared/Strip/SharedStrippableSystem.cs, Resources/Changelog/Changelog.yml, Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml, Resources/Prototypes/Entities/Clothing/OuterClothing/wintercoats.yml, Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml, Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml, Resources/Prototypes/Entities/Objects/Weapons/Throwable/clusterbang.yml
=> Upstream20241003

Resources/Changelog/Harmony.yml
=> Changelog20241003

Resources/Changelog/Harmony.yml
=> Changelog20241004

Resources/Prototypes/Loadouts/Miscellaneous/trinkets.yml, Resources/Prototypes/Loadouts/loadout_groups.yml
Added Harmonica to Loadouts under trinkets.
I was asked to.
`Resources/Prototypes/Loadouts/Miscellaneous/trinkets.yml` -- Added Harmonica to Loadout Trinkets list
`Resources/Prototypes/Loadouts/loadout_groups.yml` -- Made Harmonica selectable
**Changelog**
:cl:
- add: Added Harmonica to Loadouts under Trinkets
=> Add Harmonica to Loadouts

Resources/Changelog/Harmony.yml
=> Changelog20241006

Resources/manifest.yml
Changes the application window name to Harmony, that's literally it.
**Changelog**
no
=> Harmony Window Name

Resources/Maps/_Harmony/Shuttles/syndicate-diplomacy.yml
Added a Syndicate diplomacy craft
The shuttle is supposed to give Syndicates more of a reason to buy Syndicate encryption keys, and gives KoS roles (Nuclear Operatives, Death row Syndicate inmates) ways out of suicide, death, etc by having the chance to be spoken for by someone higher up in the Syndicate.
Only really good to be spawned in if there is a live Syndicate on death row, or admins want to make an event with NT/Syndie relations.
Comes with enough room and supplies for 1 diplomat and 1 bodyguard. Players should stick to their respective roles and not go on a killing spree (ESPECIALLY the bodyguard, who is encouraged to merely stick by the diplomat's side, rescue them, and be muscle for negotiations.)
Has the ID of Syndicate-diplomacy in the _Harmony/Shuttles tab.
Fixed the broken …
=> Add Syndicate Diplomacy ship for Admin spawning.

Resources/Changelog/Harmony.yml
Changelog update for latest PRs
=> Changelog update 17102024

Resources/ServerInfo/Guidebook/ServerRules/HarmonyRules/HarmonyR6.xml, Resources/ServerInfo/Guidebook/ServerRules/HarmonyRules/HarmonyRules.xml, Resources/ServerInfo/Guidebook/ServerRules/HarmonyRules/HarmonyS4.xml
Admin voted rules changes, and adjusting AI law rule to be more in line with the current version of the game, and after taking some discord feedback about it. 
**Changelog**
:cl:
- tweak: Clarified EORG rules further, and tweaked the AI law change rule.
=> Minor rule change and clarification

Resources/Maps/Nonstations/nukieplanet.yml
Added labeler to nukie outpost
After weeks of asking admins to spawn a labeler for me, I realized I can just do it myself.
I can't put it in _Harmony subfolder because nukieplanet.yml is directly referenced in nukeops gamerule in roundstart.yml, and I can't override something from it without creating a whole new gamerule. To make this change work from within _Harmony subfolder, I'd have to create a new gamerule, a new preset that references new gamerule instead of the upstream one, and admins would have to remember to load this new preset instead of upstream one, which is an unreasonably large changeset(and additional unnecessary thing for admins to remember) as opposed to just changing the upstream file directly.
**Changelog**
=> Added labeler to nukie outpost

Resources/Changelog/Harmony.yml
=> Changelog22102024

Resources/Changelog/Harmony.yml
=> Changelog20241027

Resources/Changelog/Harmony.yml
=> Changelog30102024

.github/CODEOWNERS
Temporary. To be improved with teams
=> CODEOWNERS change

Resources/Maps/_Harmony/xeno.yml, Resources/Prototypes/_Harmony/Maps/xeno.yml
Xeno Beta 1.3.4
- Added Reporter slots
- Added Pun Pun
- Added Space Cleaner Dispenser in Janitorial
- Added more/moved cameras around the station
- Added perma cryo bed
- Added reagent grinder to botany
- Changed AI upload to be (a little) safer
- Security SMES now has a name
- Provided more materials + igniter to Atmospherics
- Replaced high capacity fuel tank in Engineering with a normal one
- Added an emergency crowbar to the spaced cargo belt area
- Added some lights to improve visibility (most notably outside disposals)
- Changed Chapel xeno doors to look like service department doors
- Other minor changes/things I've forgotten
**Changelog**
:cl:
- fix: Xeno map has been updated with correct jobs, Pun Pun and minor additions/changes
=> Xeno Beta 1.3.4

Content.Server/Traits/TraitSystem.cs, Content.Shared/Traits/TraitPrototype.cs, Resources/Locale/en-US/_Harmony/traits/traits.ftl, Resources/Prototypes/_Harmony/Traits/speech.yml
- Minor change to Trait protoype and system
- Added "Raised by *" character traits that replace speech sound and verbs. Costs 1 speech trait point
- Added "Voice of *" character traits that fully replace speech sounds, verbs, emote sounds, and allowed emotes (where applicable). Costs 2 speech trait points
Basically, one is a light change, other is a full change.
Should enable new role play capabilities.
As a side effect allows people to replace an annoying speech sound but continue to play the species. (Lilten and vox situation that prompted the PR) 
- `Content.Server/Traits/TraitSystem.cs` had the boolean for replacing the existing component hard coded to false.
Introduced a `ReplaceComponents` boolean that controls this behavior in `Content.Shared/Traits/TraitPrototype.cs` as we need to …
=> Add Raised by [species] and Voice of [species] character traits

Resources/Changelog/Harmony.yml
=> Changelog20241104 Part 2

Resources/ServerInfo/Guidebook/ServerRules/HarmonyRules/HarmonyR1.xml, Resources/ServerInfo/Guidebook/ServerRules/HarmonyRules/HarmonyR2.xml, Resources/ServerInfo/Guidebook/ServerRules/HarmonyRules/HarmonyR3.xml, Resources/ServerInfo/Guidebook/ServerRules/HarmonyRules/HarmonyR4.xml, Resources/ServerInfo/Guidebook/ServerRules/HarmonyRules/HarmonyR5.xml, Resources/ServerInfo/Guidebook/ServerRules/HarmonyRules/HarmonyR6.xml, Resources/ServerInfo/Guidebook/ServerRules/HarmonyRules/HarmonyR7.xml, Resources/ServerInfo/Guidebook/ServerRules/HarmonyRules/HarmonyR8.xml, Resources/ServerInfo/Guidebook/ServerRules/HarmonyRules/HarmonyRules.xml
Updated server rules to newly written versions.
This rules rewrite has taken place over the course of a few weeks and aims to improve clarity, especially in the areas of difference between Harmony and WizDen (upstream).
**Changelog**
:cl:
- tweak: Server rules have been updated for better clarity.
=> Rules Update

Resources/Changelog/Harmony.yml
=> Changelog20241107

Resources/Changelog/Harmony.yml
=> Changelog20241111

Resources/Changelog/Harmony.yml
=> Changelog20241113

Resources/Changelog/Harmony.yml
=> Changelog20241114

Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml, Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLRestrictedList.xml
Fixed typos and added information about harmony specific features, if there are any more harmony features that I missed let me know and I can add them.
**Changelog**
=> Update guide book

Resources/Changelog/Harmony.yml
=> Changelog20241116

Resources/Changelog/Harmony.yml
=> Changelog20241118

Resources/Prototypes/_Harmony/Catalog/Cargo/cargo_armory.yml
Increased RSC crate cost to 2400
**Changelog**
=> Fix for arbitrage test failure on RSC crate

Resources/Changelog/Harmony.yml
=> Changelog20241120

Resources/Changelog/Harmony.yml
=> Changelog20241125

Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLCrimeList.xml, Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml
Updates in game space law to reflect the current one on the wiki
**Changelog**
:cl:
- tweak: Updated space law to reflect the current version on the wiki.
=> Space Law Revision

Resources/Changelog/Harmony.yml
=> Changelog20241205

Resources/Changelog/Harmony.yml
=> Changelog20241208

Resources/Changelog/Harmony.yml
=> Changelog20241225

Resources/Changelog/Harmony.yml
=> Changelog20241230

Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml
- Adds the HoS Flask to the HoS Armored Trench Coat Pocket
I made a new sprite for it and want it to be seen. There totally isn't something wrong with that!
Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml -- Adds the HoS Flask to the HoS Armored Trench Coat Pocket
N/A
**Changelog**
:cl:
- add: Added the HoS Flask to the HoS Armored Trench Coat Pocket
=> Adds the HoS Flask to the HoS Armored Trench Coat Pocket

Resources/Prototypes/Objectives/thief.yml
Reverts ss14-harmony/space-station-14#259
Already fixed upstream in a different manner
=> Revert "Make theifs no longer have objectives for animals who dont exist"

Resources/Changelog/Harmony.yml
=> Changelog20250106

Resources/Prototypes/_DeltaV/Entities/Objects/Devices/pda.yml
Quick fix for the pda yaml I merged without checking. Oops.
=> Fix SyndiListeningPostPDA to work with chameleon pda system

Resources/ServerInfo/Guidebook/ServerRules/HarmonyRules/HarmonyR5.xml, Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml
Edits in game space law to reflect the current wiki. Also edits the evac rules to prohibit explosive of any kind after an admin vote to ban them passed. 
Our current version of space law proved somewhat unpopular. It allowed for antags to more or less get away with an infinite number of crimes without fear of major punishment. It also took away agency from lawyers to be able to argue for different sentences, as the previous version of space law only cared about a singular crime in a list of crimes.
New space law is very similar to the previous system used on Harmony. The major changes are, only those who commit capital offenses may be put in the permanent brig or become eligible for execution. However, repeat crimes now will elevate your crime tier by one. For example if you are arrested …
=> Space law and minor rule changes

Resources/Changelog/Harmony.yml
=> Changelog20250108

LEGAL.md, README.md, Resources/Audio/_Harmony/Lobby/attributions.yml, Resources/Changelog/Harmony.yml, Resources/Textures/_Harmony/LobbyScreens/attributions.yml
`ss14-harmony/space-station-14 -> ss14-harmony/ss14-harmony`
=> Repo rename

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
Largely based on DeltaV Guidelines: https://github.com/DeltaV-Station/Delta-v/blob/master/CONTRIBUTING.md
Changes PR Template and README to reflect the existence of CONTIBUTING.md
Preview of rendered MD: https://github.com/ss14-harmony/ss14-harmony/blob/contributing-md/CONTRIBUTING.md
We are at the point when we need those.
N/A
N/A
**Changelog**
=> Add CONTRIBUTING.md

Resources/Audio/StationEvents/attributions.yml, Resources/Audio/_Harmony/StationEvents/attributions.yml, Resources/Prototypes/SoundCollections/NukeMusic.yml
Adds new song to the game
https://github.com/user-attachments/assets/86b24de6-9254-4985-9a81-55266b959714
**Changelog**
:cl:
- add: New song as the nuke approaches detonation.
=> New nukie song, Moodswings, by me.

Resources/Changelog/Harmony.yml
=> Changelog20250112

Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Halved the tarantula poison injection from 3 to 1.5 units per bite. This is still twice as much as it was before original buff (which quadrupled the injection).
This PR is here in draft state just in case gameplay testing will show that tarantulas are too strong now.
**Changelog**
=> Toning down giant spider poison injection

Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/pistol.yml
- Pistol magazines now hold 15 bullets instead of 10
Security tends to arm up over the smallest inconveniences that could just be dealt with using your normal side arm (If it wasn't garbage). This also makes the Viper stronger for Syndicate Agents. This on top of https://github.com/ss14-harmony/ss14-harmony/pull/287 will make shields even more viable.
Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/pistol.yml -- Changes .35 Pistol Magazine Capacity from 10 to 15
https://youtu.be/Fxreyc_nG3E
**Changelog**
:cl:
- tweak: Increases the .35 pistol magazine from 10 to 15
=> Increases .35 Pistol Mag Size

Resources/Prototypes/Entities/Objects/Weapons/Throwable/bola.yml
Makes Bolas immune to explosion damage.
Got reports of bolas getting destroyed in people's bags when they were blown up. This feels bad for gameplay as there is no feedback besides finding your bolas gone from where they were supposed to be.
Upstream:
``Resources/Prototypes/Entities/Objects/Weapons/Throwable/bola.yml`` -- Makes bolas 100% explosion resistance
**Changelog**
:cl:
- fix: Made Bolas immune to explosions.
=> Bola Explosion Immunity

Resources/Prototypes/_Harmony/Entities/Clothing/Hands/gloves.yml
=> Mantis gloves hotfix

Content.Shared/_Harmony/Clothing/Gloves/Components/MantisGlovesComponent.cs, Content.Shared/_Harmony/Clothing/Gloves/Systems/SharedMantisGlovesSystem.cs, Resources/Locale/en-US/_Harmony/clothing/mantis-gloves.ftl, Resources/Prototypes/_Harmony/Entities/Clothing/Hands/gloves.yml
Mantis gloves refactor
https://github.com/ss14-harmony/ss14-harmony/pull/338#pullrequestreview-2588347946
https://github.com/ss14-harmony/ss14-harmony/pull/351#issuecomment-2629184831
Since the gloves prototype now inherits from the latex gloves prototype, we're using the prototype name and description directly instead of copying them into .ftl. The prototype itself is a bit shorter, as we don't need some of the previous stuff that was in it anymore. Some deletions were made in the component and .ftl files as well, as those values are not used anymore. Moved PopUps values (read: locale) into component for consistency
**Changelog**
no cl no fun
=> Mantis gloves refactor

Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
Made the Sawn-Off major contraband instead of minor contraband.
Basically a meme PR, it's more of a test to see if the trade-off of size for a higher contraband rating is worth it.
``Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml`` -- Changed Sawn-Off to Major contraband
**Changelog**
:cl:
- tweak: Sawn-Off shotgun designated as major contraband
=> Adds Major Contraband to Sawn Off

Resources/Changelog/Harmony.yml
=> Changelog20250126

Content.Server/Implants/ImplantedSystem.cs, Content.Shared/Implants/Components/ImplantedComponent.cs
Early merge of https://github.com/space-wizards/space-station-14/pull/34923
Bomb implants didn't go boom.
=> Early merge of microbomb fix

Resources/Changelog/Harmony.yml
=> Changelog20250208

Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml, Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
Removes RPD from lockers until their radial menu code can be fixed.
RPDs currently brick the client when used
Removes RPDs from the locker item pool
NA
**Changelog**
=> remove rpd from lockers

Resources/Prototypes/_Harmony/Entities/Objects/Weapons/Bombs/pizzabomb.yml
- Fixes the pizza bomb's capitalization
The pizza bomb used to be easily noticeable, and nothing else in the game has a capitalized name like this.
Resources/Prototypes/_Harmony/Entities/Objects/Weapons/Bombs/pizzabomb.yml -- Fixes the pizza bomb's name
**Changelog**
:cl:
- fix: Fixed the pizza bomb's name being capitalized
=> Fixes pizza bomb capitalization

Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml
Reverts ss14-harmony/ss14-harmony#274
Flask now spawns in locker, leading to a duplicate.
=> Revert "Adds the HoS Flask to the HoS Armored Trench Coat Pocket"

Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLCrimeList.xml
Removes terrorism as a charge in Space Law. 
The charge is very subjective, and is often used incorrectly or in situations that a lesser charge would have been more appropriate. This law was also written for a different use case in space law which is now gone. There are still three other capital crimes, and other crimes can stack into capital crimes. This should reduce perma sentences just a little bit, or make perma sentences require more hard evidence to stick.
**Changelog**
:cl:
- remove: Removed Terrorism from the list of crimes under space law.
=> Removed Terrorism Law

Resources/Prototypes/Maps/convex.yml, Resources/Prototypes/Maps/elkridge.yml
I have added the prisoner to convex and elkridge
These maps have the perma beacon in the right place and have a high enough population for the prisoner to be fine
**Changelog**
=> Add the prisoner to more maps

Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml, Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml, Resources/Prototypes/_Harmony/Entities/Clothing/Uniforms/jumpskirts.yml
Fix the test failures on master
And some formatting issues because rider decided to and it should be fine
99% of coders quit before they fail it big!
**Changelog**
=> Fix the tests

Resources/Maps/_Harmony/Shuttles/ShuttleEvent/brigmedic.yml
- Fixes the shuttle console on the brigmedic shuttle
- Adds a bolt signaler to the brigmedic shuttle
Spakny want this in new PR!
_Harmony Namescape
Resources/Maps/_Harmony/Shuttles/ShuttleEvent/brigmedic.yml -- Fixes the brigmedic shuttle
**Changelog**
:cl:
- fix: Fixed the brigmedic shuttle so it has the proper shuttle console
=> Brigmedic Shuttle Hotfixes

Resources/Maps/_Harmony/mira.yml
Some more hotfixes for Mira station:
- Added wiring near AI maints, due to there not being any
- Added some atmospheric signs to the respective miners/gas containers, so it's easier to distinguish
- Changed out RD's locker with the filled version
- Added some decor around the departments
- Configured a vent/scrubber to bar maintenance
**Changelog**
=> Mira hotfixes - V2.1

Resources/Maps/_Harmony/atlas.yml
Fixed some minor issues, such as chapel not spawning with an altar and substations/APCs not being named. Also made communications accessible by the engineering department.
These should be the final changes before engineering gets a major rework. Will push more minor changes beforehand if needed.
**Changelog**
🆑 Atlas fixes!
=> Atlas update #2

Content.Client/RCD/RCDMenu.xaml, Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml, Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
This fixes the radial menu of RPDs to use the new radial menu syntax introduced in [upstream PR 32653](https://github.com/space-wizards/space-station-14/pull/32653). This also reverts the hotfix PR I made when the issue was first identified #369 (nice).
I have tested every RPD radial menu button on my device, and with this patch I no longer have my client crash or other issues.
Bugfixes are good, and this makes it so that players can use the RPD without crashing their client.
I made some changes to RCDMenu.xaml so it now uses the new radial menu syntax. I also added markings that this is a Harmony specific change as it is not from upstream.
**Changelog**
=> Fix rpd radial menu and add it back to lockers

Content.Client/RCD/RCDMenuBoundUserInterface.cs
Fixed the RPD
Webedit ops go! (don't worry I still ran a local client to check)
The walls and flooring button is currently needed because it holds the deconstruction tool and fixing that is outside of my pay grade.
**Changelog**
=> Fix the RPD

Resources/Maps/_Harmony/Nonstations/listening-outpost.yml
Adds Handheld GPS, cryosleep, botany QoL fixtures and paper variety to listening post
With listening post spawning at 20 minutes instead of 60, the risk of operatives growing weary and lowering round quality with shitposting increases, added cryo to listening post to alleviate this issue.
Botany now has a bucket, papercane seeds, beaker box and grinder as a small QoL to avoid biogenerator liquid spills and  to expand on available recipes.
Handheld GPS added to listening post engineering, as there was currently no way for operatives to identify their own location relative to the station. The introduction document mentioned being careful with revealing it's location, but there was no way to identify the facilities location. Knowing where the post is will allow for more station/listening …
=> Listening post update

Content.Shared/_Harmony/EntitySelector/EntitySelector.cs
I accidentally made entity selectors require all of their sub-selectors to match instead of just one in the map modification PR. This PR fixes that.
**Changelog**
=> Small map modification fix

Resources/Prototypes/Loadouts/loadout_groups.yml, Resources/Prototypes/_Harmony/Loadouts/Miscellaneous/trinkets.yml
Adds the cane as option in the loadouts.
It's a nice RP item to have for those who wish to have nice drip or RP being older and needing extra assistant.
Added the cane to trinkets.yml and loadout_group.yml
**Changelog**
🆑MoonlightHollow
- add: Added the cane
=> Added the cane to loadouts.

Resources/Prototypes/Catalog/uplink_catalog.yml
Added and remove some items from the surplus blacklist
There some items blacklisted from the surplus for little reason and added something to blacklist that were just wasted.
Adds to blacklist:
Fake Syndicate Bomb
Singularity Beacon
Syndi-Cat
Removes from blacklist:
Cane Sword
Thanks Diesel for list.
Added various blacklist and and committed some blacklist to items.
**Changelog**
:cl:
- tweak: Added and remove surplus blacklist
=> Rebalance Surplus Blacklist

Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/shotgun.yml
- Makes slugs deal more pierce damage
- Slugs now do structural damage and have structure piercing
Slugs are bad and needed a buff. By giving them structural damage and structure pierce, it gives them more utility.
Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/shotgun.yml -- Updates the slug's damage types
https://youtu.be/n3J-ZfDN0NY
**Changelog**
- tweak: Makes shotgun slugs do more damage
- tweak: Shotgun slugs now deal structural damage and can pierce through weaker structures
=> The Sluggening

Resources/Prototypes/Entities/Clothing/Neck/cloaks.yml, Resources/Prototypes/_Harmony/Recipes/Construction/Graphs/clothing/goliath_cloak.yml, Resources/Prototypes/_Harmony/Recipes/Construction/clothing.yml
Goliath cloaks are now craftable with goliath hide
Goliath cloaks are cool and you should be able to obtain them during a normal round.
Resources/Prototypes/Entities/Clothing/Neck/cloaks.yml - added construction component for graph
Resources/Prototypes/_Harmony/Recipes/Construction/Graphs/clothing/goliath_cloak.yml - addec construction graph
Resources/Prototypes/_Harmony/Recipes/Construction/clothing.yml - added recipe
https://github.com/user-attachments/assets/ef1e8ff0-d543-47e4-a788-4bd7a4ca254d
**Changelog**
:cl:
- tweak: Goliath cloaks are now craftable
=> makes goliath cloaks craftable

Resources/Prototypes/_Harmony/Recipes/Reactions/medicine.yml
Gives barozine its own Vestine-based recipe
It's something that was talked about in Harmony general a few days ago, and I think it could lead to webvests and riot suits being used more by both traitors and nukies
Resources/Prototypes/_Harmony/Recipes/Reactions/medicine.yml -- Adds the Barozine Recipe
**Changelog**
:cl:
- add: Gives Barozine its Own Vestine-Based Recipe
=> Gives Barozine its Own Vestine-Based Recipe

Resources/Prototypes/Entities/Objects/Devices/pda.yml
Added the AstroNav as a preinstalled cartridge to syndicate & syndicate agent PDAs.
Syndicate & syndicate agent PDAs are most commonly found on Nuclear Operatives who can sometimes get lost from each other in the right situations, especially in space.  Giving syndicate PDAs AstroNav lets the Nuclear Operatives able to regroup faster and much easier than without AstroNav.
Note: This effects anything that uses the SyndiPDA as a base, which mainly includes Syndicate Refugees and Listening Post Operators.  This means that they'll also get AstroNav preinstalled, however compared to Nukies it's felt that the advantage of having it negligible.
Added AstroNavCartridge to preinstalled in SyndiPDA & SyndiAgentPDA.
**Changelog**
:cl:
- add: Added AstroNav to syndicate & syndicate agent PDAs.
=> Added AstroNav to syndicate & syndicate agent PDAs

Resources/Prototypes/_Harmony/Catalog/uplink_catalog.yml
Fix the tests.
`ClothingBackpackDuffelSyndicateRaidBundle` was renamed to `ClothingBackpackSyndicateRaidBundle`
**Changelog**
=> Tests are great

Resources/Changelog/Harmony.yml
=> Changelog update 20250501 v2

Resources/Prototypes/Reagents/narcotics.yml
Buffed Hyperzines metabolism to have a rate of .5 instead of 1.
There was talk in the discord that hyperzine was weak compared to other stimulants like meth while being a syndicate chemical.
Changed one line in narcotics.yml. 
No media needed, its just a number going down by .5 instead of 1.
**Changelog**
:cl:
- tweak: Tweaked Hyperzines metabolism to be .5.
=> Buffed Hyperzine

Resources/Changelog/Harmony.yml
Update the changelog.
Preferably merge before harmup.
=> Changelog20250502

Resources/Changelog/Harmony.yml
Changelog update for the 5th of May 2025
=> Changelog20250505

Resources/Prototypes/Entities/Mobs/Player/silicon.yml
Reduced the chance for ion storms to affect the AI
Requested by two admins
**Changelog**
:cl:
- tweak: The AI is now less likely to get affected by an ion storm.
=> Make ion storms affect the AI less often

Resources/Prototypes/_Harmony/Loadouts/Jobs/Cargo/cargo_technician.yml, Resources/Prototypes/_Harmony/Loadouts/Jobs/Civilian/librarian.yml
Fixed cargo being unaffected by the seniority items timer change
Cleaned up the role timer comments for the librarian
**Changelog**
:cl:
- fix: The cargo department is no longer unaffected by the seniority item timer changes.
=> Fix cargo seniority item timers

Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
Fixed ERT hardsuit helmets showing up as error sprites when worn
The issue was caused by the syndicate hardsuit helmets being modified to use a completely different layering system which propagated to the ERT hardsuit helmets even though they weren't compatible.
I have created a shared base for all ERT hardsuit helmets which is no longer based on the syndicate hardsuits and is equivalent to the syndicate parent. I have also changed all ERT hardsuit helmets to use this base as a parent instead.
**Changelog**
:cl:
- fix: ERT hardsuit helmets will no longer show up as error sprites.
=> Fix ERT hardsuit helmets

Resources/Prototypes/GameRules/events.yml, Resources/Prototypes/GameRules/roundstart.yml, Resources/Prototypes/GameRules/subgamemodes.yml
Raised the minimum pop it takes to spawn a wizard from 10 to 25.
While is the wizard is a very rare antagonist, they're practically guaranteed on survival rounds. Nukies require a minimum amount of 20 people to be readied up before the round starts, and a LoneOp needs 35 people present within the round. Raising the minimum player count should help prevent a random wizard from steam rolling a 10 person crew. 
N/A
**Changelog**
:cl: Wizard gamerule tweak
=> Raise the amount of minimum players it takes to spawn a wizard.

Content.Server/Shuttles/Components/ShuttleComponent.cs, Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs, Content.Server/Shuttles/Systems/ShuttleSystem.cs, Content.Shared/Anomaly/SharedAnomalySystem.cs, Content.Shared/Movement/Events/TileFrictionEvent.cs, Content.Shared/Movement/Systems/SharedMoverController.Input.cs, Content.Shared/Movement/Systems/SharedMoverController.cs
Early merge with upstream stable for the commits space-wizards/space-station-14@45253ca79ed7a03d43716bc63908ffe90c8c7ce1, space-wizards/space-station-14@61adee05f6e50088ffeb25fdc54da188ae689043, and space-wizards/space-station-14@494861dc3d938b752567bead5bf40132fba03107
They seem like some pretty nice hotfixes to have
=> Early merge for hotfixes

Resources/Prototypes/_Harmony/Maps/Modifications/amber.yml
Fixed the prisoner spawning inside the walls on amber station.
**Changelog**
:cl:
- fix: The prisoner will no longer spawn inside of the walls on amber.
=> Fix amber prisoner spawning

Content.IntegrationTests/Tests/PostMapInitTest.cs
Cleans up formatting in `PostMapInitTests.cs` and adjusts comment of Aspid to reflect new dev
=> Clean up PostMapInitTest.cs

Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml, Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml, Resources/Prototypes/_Harmony/Entities/Clothing/Back/satchel.yml
I gave the admin bags 100% explosion resistance to contents.
Also added the super door remote to the bag because SPANKY is telling me to scope creep my PRs
https://medal.tv/games/space-station-14/clips/klxeEKlBxnJ55RAXZ?invite=cr-MSxMcnYsMTYzOTEzMzU
**Changelog**
=> Give admin bags explosion resistance

Resources/Locale/en-US/_Harmony/store/uplink-catalog.ftl, Resources/Prototypes/_Harmony/Catalog/uplink_catalog.yml
- Adds Shotgun Drums to the Uplink
Every other gun has spare ammo, why not the bulldog?
Resources/Locale/en-US/_Harmony/store/uplink-catalog.ftl -- Adds names and descriptions for the shotgun drums
Resources/Prototypes/_Harmony/Catalog/uplink_catalog.yml -- Adds shotgun drums to the uplink
**Changelog**
:cl:
- add: Adds Pellet and Slug Shotgun Drums to the Uplink
=> Adds Shotgun Drums to the Uplink

Resources/Prototypes/secret_weights.yml
Changed gamemode percents. Took 3 from tots and added 2 to zombies and 1 to zombmeteors
We hardly see zombies. This would allow for us to see them slightly more and added a slightest bump to zombmeteors. Plus there were new changes to zombies so it is a slightly better gamemode now.
Changed some values in secret_weights.yml.
Doesn't need any, just some percent changes.
**Changelog**
:cl:
- tweak: Made zombies and zombmeteors slightly more common.
=> Upped Zombie Percent

.github/CODEOWNERS
I need codeowner for rules and guidebook stuff
Also a lot of minor changes add FTL files and it's annoying to need to bug another maintainer for those.
**Changelog**
Not player facing
=> CODEOWNERS: Jajsha ownership of locale and Jajsha+Spanky ownership of server rules

Resources/Prototypes/Actions/polymorph.yml
The upgrades for jaunt come with the new abilitity to use them while cuffed or down
Right now the current jaunt upgrades just decrease the cooldown, which isnt a very worthwhile purchase, this will create more of a choice between upgrading it or getting another spell. as its a morth worthwhile upgrade
Resources/Prototypes/Actions/polymorph.yml - changes jaunt to work while downed or cuffed
https://github.com/user-attachments/assets/2b1fb6cb-93d5-4b47-99da-2c7b6f0ae82d
**Changelog**
:cl:
- tweak:  Upgrading Jaunt now allows you to use it while cuffed or down
=> Jaunt II & III now allow you to use them when cuffed or down

Resources/Prototypes/_Harmony/Entities/Structures/Machines/microwave.yml
Micheals can now be examined for how much wave they will do on hit.
Micheal-waves are much loud when hit self-antag greytide.
Microwaves not showing their damage can be quite unintuitive to players.
Microwaves being able to be used as basically silent gibbing machines is also not great.
https://github.com/user-attachments/assets/f325da41-8d15-4860-a189-c780b8a0eb7a
**Changelog**
=> Small micheal tweaks

Resources/Prototypes/GameRules/roundstart.yml
=> Add BB to the no wizard sub game modes 

Resources/Prototypes/_Harmony/GameRules/subgamemodes.yml
This is what I get for copying the antag selection definition from thieves.
Thieves will no longer become blood brothers.
**Changelog**
:cl:
- tweak: Thieves will no longer become blood brothers.
=> Exclusiver blood brother

Resources/Prototypes/Catalog/Bounties/salvage_jobs.yml, Resources/Prototypes/Research/arsenal.yml
Re-balanced some recent salv additions. Most notably the pka mods are now t1 sci and the bounties require less to complete.
After talking on discord with resident salv players, I decided to put a bandaid patch on these until we decide what to do going forward. Also some of these were just egregious and most people want the upgrades to be in T1 sci.
Resources/Prototypes/Research/arsenal.yml : Changes Pka mods to be t1 sci
Resources/Prototypes/Catalog/Bounties/salvage_jobs.yml : Re-balanced the amounts needed.
I dont believe this needs media.
**Changelog**
:cl:
- tweak: Made PKA Mods T1 Arsenal
- tweak: Re-balanced Salvage Job Amounts
=> Re-balanced Salv

Resources/Maps/_Harmony/prime.yml
There was no wiring here. Everything was unpowered.
https://github.com/user-attachments/assets/0be9a84c-cf1b-4a0e-9867-7bb4c93eada1
The lights now work properly. They start off and then turn on ONLY when the door is open.
**Changelog**
=> Prime - Misc security fixes

Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
resolves #562, adding missing comments from #219 
Changes should be properly documented to make it easier for maintainers and contributors
Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml - added comments
**Changelog**
None required
=> Fixes missing comments in Hardsuit.yml

Resources/Prototypes/_Harmony/GameRules/subgamemodes.yml
The blood brothers gamerule will no longer allow non-humanoids to turn into blood brothers.
The code in this PR is available under the MIT license.
**Changelog**
:cl:
- fix: Non-humanoids can no longer become blood brothers.
=> Fix animals becoming blood brothers

Resources/ServerInfo/_Harmony/Guidebook/ServerRules/HarmonyRules/HarmonyR5.xml
Updates rules in game to reflect recent rulings and to match the wiki.
=> Update rules concerning looses. 

Resources/Prototypes/_Goobstation/Entities/Clothing/Head/hardsuit-helmets.yml, Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/hardsuits.yml
=> Fix the cybersun stealth suit spamming errors when worn

Resources/Changelog/Harmony.yml, Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml, Resources/Prototypes/Entities/Structures/Wallmounts/WallmountMachines/screen.yml, Resources/Prototypes/Entities/Structures/Wallmounts/WallmountMachines/station_map.yml
Merge a pretty important hotfix
Do not squash
=> Merge hotfixes

Content.IntegrationTests/AssemblyInfo.cs, Content.Shared/Standing/StandingStateSystem.cs, Resources/Prototypes/Entities/Structures/Wallmounts/Switches/switch.yml
Merge some pretty damn important hotfixes
=> Hotfix merge

Content.Server/Nutrition/EntitySystems/CreamPieSystem.cs, Content.Server/Polymorph/Components/PolymorphedEntityComponent.cs, Content.Server/Polymorph/Systems/PolymorphSystem.cs, Content.Shared/Nutrition/EntitySystems/FoodSequenceSystem.cs, Content.Shared/Nutrition/EntitySystems/IngestionSystem.API.cs, Content.Shared/Nutrition/EntitySystems/SharedCreamPieSystem.cs, Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/pie.yml
=> Merge some hotfixes

.github/workflows/publish.yml, Tools/actions_changelogs_since_last_run.py
I got spanky to make a channel
I don't really see any reason why this wouldn't work
=> Enable the discord changelog
